name: docdoc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  # Localization
  easy_localization: ^3.0.3
  intl: any
  flutter:
    sdk: flutter
  # State management
  flutter_bloc: ^8.1.3
  # for splash screen
  flutter_native_splash: ^2.3.10
  # Code generation for immutable classes
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  # Service locator for dependency injection
  get_it: ^7.6.7
  # Generates JSON serialization boilerplate
  json_annotation: ^4.8.1
  # Networking
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  # for adapting screen and font size
  flutter_screenutil: ^5.9.0
  # An SVG rendering, which allows painting and displaying Scalable Vector Graphics
  flutter_svg: ^2.0.9

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
